declare const styles: {
	readonly "step-progress-item": string;
	readonly "step-progress-item--bullets": string;
	readonly "step-progress-item--bullets-size-s": string;
	readonly "step-progress-item--bullets-size-m": string;
	readonly "step-progress-item--bullets-size-l": string;
	readonly "step-progress-label": string;
	readonly "step-progress-label-mode-error": string;
	readonly "step-progress-label-mode-info": string;
	readonly "step-progress-label-mode-success": string;
	readonly "step-progress-label-mode-warning": string;
	readonly "step-progress-label-mode-primary": string;
	readonly "step-progress-label-mode-secondary": string;
	readonly "step-progress-label-mode-tertiary": string;
	readonly "step-progress-label-mode-black": string;
	readonly "step-progress-list": string;
	readonly "step-progress-mode-error": string;
	readonly "step-progress-mode-info": string;
	readonly "step-progress-mode-pending": string;
	readonly "step-progress-mode-success": string;
	readonly "step-progress-mode-warning": string;
	readonly "step-progress-mode-primary": string;
	readonly "step-progress-mode-secondary": string;
	readonly "step-progress-mode-tertiary": string;
	readonly "step-progress-mode-black": string;
};
export = styles;
